services:
  - type: worker
    name: linkedin-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python automated_workflow.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_TABLE_NAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false 